<form role="form" method="post">
    <div class="form-group">
        <label><?php echo __('Clear All Products Using wp_delete_post(post_id, force_delete) and wp_delete_attachment(post_id, force_delete)');?></label><br/>
        <button type="submit" class="btn btn-primary" name="clearAllProducts" value="clearAllProducts"><?php echo __('Clear All Products'); ?></button>
    </div>
    <div class="form-group">
        <label><?php echo __('Delete All Products That Have post_status = pending And KbAmzOfferSummary.TotalNew <= 0');?></label><br/>
        <button type="submit" class="btn btn-primary" name="clearAllProductsNoQuantity" value="clearAllProducts">
            <?php
            echo sprintf(
                ($this->productsNoQuantityCount == 1 ? __('Delete %s Product With No Quantity') : __('Delete %s Products With No Quantity')),
                $this->productsNoQuantityCount
            );
            ?>
        </button>
    </div>
</form>