<div class="row homepage">

    <div class="col-sm-3">
        <img src="<?php echo getKbPluginUrl(); ?>/template/admin/img/2kb-amazon-affiliate-product-logo.png" />
    </div>
    <div class="col-sm-9">
        <div class="row">
            <div class="col-sm-12" style="font-size: 16px;">
                <span class="label label-info">
                    <span class="glyphicon glyphicon-usd"></span> Products:
                    <?php echo getKbAmz()->getProductsCount(); ?>
                </span>
                &nbsp;&nbsp;
                <span class="label label-info">
                    <span class="glyphicon glyphicon-download-alt"></span> To Download:
                    <?php echo getKbAmz()->getProductsToDownloadCount(); ?>
                </span>
                &nbsp;&nbsp;
                <span class="label label-info">
                    <span class="glyphicon glyphicon-refresh"></span> To Update:
                    <?php echo getKbAmz()->getProductsToUpdateCount(); ?>
                </span>
                &nbsp;&nbsp;
                <span class="label label-info">
                    <?php
                    $hours = 0;
                    $count = getKbAmz()->getProductsToUpdateCount();
                    if ($count > 0) {
                        $per = getKbAmz()->getOption('updateProductsPriceCronNumberToProcess');
                        $interval = getKbAmz()->getOption('updateProductsPriceCronInterval');
                        $intervals = $count / $per;
                        $intervalHours = 1;
                        if ($interval == 'twicedaily') {
                            $intervalHours = 12;
                        } else if ($interval == 'daily') {
                            $intervalHours = 24;
                        }
                        $hours = ceil($intervals . $intervalHours);
                    }

                    ?>
                    <span class="glyphicon glyphicon-time"></span> Time To Update:
                    <?php echo $hours; ?>h
                </span>
                &nbsp;&nbsp;
                <span class="label label-info">
                    <span class="glyphicon glyphicon-repeat"></span> Requests/Avg. Time:
                    <?php echo getKbAmz()->getOption('AmazonRequests', 1); ?>
                    /
                    <?php echo getKbAmz()->getOption('averageTimeToFetch', 1) * 1000; ?>ms
                </span>
            </div>
            <br/><br/>
            <div class="col-sm-6">
                <?php if (hasKbAmazonApiDetails()) { ?>
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-check"></span>
                        <?php echo __('Amazon API is Configured.'); ?>
                    </div>
                <?php } else { ?>
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-fire"></span>
                        <a href="?page=kbAmz&kbAction=settingsAmazonApi">
                            <?php echo __('Click to setup you Amazon API Configuration.'); ?>
                        </a>
                    </div>
                    <?php
                }
                ?>

                <?php if (getKbAmz()->getProductsCount()) { ?>

                    <?php
                    $count = getKbAmz()->getProductsCount();
                    $publishedCount = getKbAmz()->getPublishedProductsCount();
                    $max = getKbAmz()->getOption('maxProductsCount');
                    ?>

                    <?php if ($max > $count && $count > $max * 0.8) { ?>
                        <div class="alert alert-warning">
                            <span class="glyphicon glyphicon-check"></span>
                            <?php echo sprintf(__('You have %s of %s products.'), getKbAmz()->getProductsCount(), getKbAmz()->getOption('maxProductsCount')); ?>
                        </div>
                    <?php } else if ($count < $max) { ?>
                        <div class="alert alert-success">
                            <span class="glyphicon glyphicon-check"></span>
                            <?php echo sprintf(__('You have %s of %s products.'), getKbAmz()->getProductsCount(), getKbAmz()->getOption('maxProductsCount')); ?>
                        </div>
                        <?php
                    } else {
                        ?>
                        <div class="alert alert-danger">
                            <span class="glyphicon glyphicon-check"></span>
                            <?php
                            $params = $_GET;
                            $params['kbAction'] = 'premium';
                            echo sprintf(
                                    __('You have %s of %s products. You can upgrade from <a href="?%s">here</a>.'), getKbAmz()->getProductsCount(), getKbAmz()->getOption('maxProductsCount'), http_build_query($params)
                            );
                            ?>
                        </div>
                        <?php
                    }
                    ?>
                    <?php if ($publishedCount == 0): ?>
                        <div class="alert alert-danger">
                            <span class="glyphicon glyphicon-check"></span>
                            <?php
                            $params = $_GET;
                            $params['kbAction'] = 'productsVisibility';
                            echo sprintf(
                                __('You have 0 of %s published products. Recommended action <a href="?%s">publish</a>.'),
                                $count,
                                http_build_query($params)
                            );
                            ?>
                        </div>
                    <?php else: ?>
                        <div class="alert alert-success">
                            <span class="glyphicon glyphicon-check"></span>
                            <?php echo sprintf(__('You have %s of %s published products.'),
                                $publishedCount,
                                $count); ?>
                        </div>
                    <?php endif; ?>
                <?php } else { ?>
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-fire"></span>
                        <a href="?page=kbAmz&kbAction=importBySearch">
                            <?php echo __('You have no products imported. Click here to start importing Amazon Products.'); ?>
                        </a>
                    </div>
                    <?php
                }
                ?>
            </div>

            <div class="col-sm-6">
                <?php if (extension_loaded('soap')) { ?>
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-check"></span>
                        <?php echo __('SOAP extension is activated on this server.'); ?>
                    </div>
                <?php } else { ?>
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-fire"></span>
                        <?php echo __('SOAP extension is not activated for this server. Please contact your hosting company and request activation.'); ?>
                    </div>
                    <?php
                }
                if (function_exists('curl_init')) {
                    ?>
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-check"></span>
                        <?php echo __('cURL extension is activated for this server.'); ?>
                    </div>
                    <?php
                } else {
                    ?>
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-fire"></span>
                        <?php echo __('cURL extension is not activated for this server. Please contact your hosting company and request activation.'); ?>
                    </div>
                    <?php
                }

                if ((int) ini_get('allow_url_fopen') > 0) {
                    ?>
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-check"></span>
                        <?php echo __('allow_url_fopen is enabled. This option allows product`s images download.'); ?>
                    </div>
                    <?php
                } else {
                    ?>
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-fire"></span>
                        <?php echo __('allow_url_fopen is disabled. This option allows product`s images download. Please contact your hosting company and request activation.'); ?>
                    </div>
                <?php }
                ?>
            </div>
        </div>
    </div>
</div>

<?php if (getKbAmz()->getOption('showStatsDataJoinModal')) : ?>
<div class="modal fade" id="stats">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php echo __('Plugin Experience'); ?></h4>
            </div>
            <div class="modal-body">
                <p style="font-size: 1.2em;">
                    <?php echo __('Do you want to participate in <b>Improving Plugin Experience Program</b> by Sending Us Data?'); ?>
                    <br/>
                    <?php echo __('You can turn this option off at any time from the setting menu.'); ?>
                </p>
            </div>
            <div class="modal-footer">
                <?php
                $_GET['improvePluginExperience'] = 1;
                unset($_GET['kbAction']);
                $_GET['kbAction'] = 'improve';
                ?>
                <a href="?<?php echo http_build_query($_GET); ?>" class="btn btn-primary">Yes</a>
                <?php
                $_GET['improvePluginExperience'] = 0;
                ?>
                <a href="?<?php echo http_build_query($_GET); ?>" class="btn btn-default">No</a>
                <?php
                unset($_GET['improvePluginExperience']);
                ?>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    (function ($) {
        $('#stats').modal('show');
    })(jQuery);
</script>
<?php endif; ?>