<div class="row" id="kb-amz-version">
    <div class="col-sm-12">
        <h4>1.0.4</h4>
        <ul style="list-style-type: disc;">
            <li>Some bugs got fixed. Thank you for your support.</li>
        </ul>
        <h4>1.0.3</h4>
        <ul style="list-style-type: disc;">
            <li>New Option = Download Images. This option allows you to store only the link of product`s images. This will save you space and time to import.</li>
            <li>Maintenance fixes.</li>
            <li>lib/KbAmazonImage</li>
            <li>lib/KbAmazonImages</li>
        </ul>
    </div>
    <div class="col-sm-12">
        <h4>1.0.2</h4>
        <ul style="list-style-type: disc;">
            <li>Dashboard info update - products counts, products to download, products to sync, time to sync.</li>
        </ul>
    </div>
    <div class="col-sm-12">
        <h4>1.0.1</h4>
        <ul style="list-style-type: disc;">
            <li>Front scripts are no longer loaded in admin.</li>
            <li>Products -> Short Codes, restore default content shortcodes. Option to replace content shortcode with the product content insuring better SEO and editability.</li>
        </ul>
    </div>
    <div class="col-sm-12">
        <h4>1.0.0</h4>
        <ul style="list-style-type: disc;">
            <li>First public version of the plugin</li>
            <li>Import products by amazon - ASIN, Search, Url Import (beta)</li>
            <li>Product attributes management and attributes restriction</li>
            <li>All products short codes management</li>
            <li>Cron job for similar products import and price update</li>
            <li><a href="?page=kbAmz&kbAction=productsShortCodes">Shortcodes</a></li>
            <li>Widgets for products filtering - Slider and Attributes filter</li>
            <li>Automatic products growing. Using similar products, this plugin will download products without you need to do anything.</li>
        </ul>
    </div>
</div>